# Generated by Django 5.2.6 on 2025-09-24 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=160, verbose_name='Nome do aluno')),
                ('operator_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Operador responsável')),
                ('type', models.CharField(choices=[('elogio', 'Elogio'), ('reclamacao', 'Reclamação'), ('sugestao', 'Sugestão')], max_length=12, verbose_name='Tipo de feedback')),
                ('course_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Curso')),
                ('class_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Turma')),
                ('subject', models.CharField(choices=[('financeiro', 'Financeiro'), ('atendimento', 'Atendimento'), ('plataforma', 'Plataforma'), ('conteudo', 'Conteúdo'), ('eventos', 'Eventos'), ('outros', 'Outros')], max_length=20, verbose_name='Assunto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('resolvido', 'Resolvido')], default='pendente', max_length=12, verbose_name='Status')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedbacks/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Autor')),
                ('comment_text', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.feedback')),
            ],
        ),
    ]
